### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by TopchetoEU** [TopchetoEU/java-jscript#24]
Currently, the engine has good ES5 support. However, for any real-world application having ES6 support is imperative.

The following features ought to be implemented:

- [x] Arrow functions (#26)
- [x] Default arguments (#26)
- [x] Spread arguments (#26)
- [x] ES6-style variable declarations (let and const) (#26)
- [x] Variable, parameter and assignment deconstructions (#28)
- [x] Object literal shorthands, methods and computed keys (#28)
- [ ] Class definitions (#29 WIP)
- [ ] Array deconstructors
- [ ] Spread syntax in objects
- [ ] Spread syntax in arrays
- [ ] Spread syntax in calls (and dynamic argument count in calls)
- [ ] Nullish coalescing operator and assignment (??)
- [ ] Optional indexing (.?)
- [ ] &&= and ||= operators (ES5 features that are missing)
- [ ] Generator functions
- [ ] new.target
- [ ] Exponent operator
- [ ] For-of loop
- [ ] Optional parsing mode for ES module files

The following will NOT be implemented:
- eval() - brings multiple complexities into the project, mostly with the resolution of variables in the runtime, for the benefit of a feature which is unsafe and has the better alternative of the Function constructor
- Non-strict context (aka JS code will be compiled and run "use strict" implied)
